### ISSUE TITLE
controllable generation?

### ISSUE THREAD

**Issue by thomas-happify** [chujiezheng/UniModel#1]
Hi there,

after did some digging, I was wondering if it's possible to do controllable generations by specifying `tgt_*`?
so basically skip `self.encode()` during inference, and provide our own target EM, CM, and DA?

Thanks

**Comment by chujiezheng** [comment]
Yes, you can make it.

We use the context to predict the response’s factors mainly in order to ensure the validness of the factor combination. Nevertheless, you can assign the factors as you want to control the response generation.

**Comment by chujiezheng** [comment]
But note that self.encode() is also inputting the context into GPT-2! It cannot be skipped. You can assign the factors in self.predict_*()

**Comment by thomas-happify** [comment]
@chujiezheng 
I thought so, thanks for the clarification!!
